/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import { useRef, useEffect, useCallback, useState } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import islandScene from '../assets/3d/island.glb'

const Island = ({ isRotating, setIsRotating, onHouseClick, ...props }) => {
  const islandRef = useRef();
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(islandScene);
  const [houseHovered, setHouseHovered] = useState(false);
  const pointerDownPos = useRef({ x: 0, y: 0 });

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;
  const floatOffset = useRef(0);

  useEffect(() => {
    document.body.style.cursor = houseHovered ? "pointer" : "auto";
    return () => { document.body.style.cursor = "auto"; };
  }, [houseHovered]);

  // Handle pointer (mouse) events for drag rotation
  // Only handle events that start on the island itself (via onPointerDown on the group)
  const handlePointerDown = useCallback((e) => {
    // Don't intercept events from other objects (Bird, hotspots, etc.)
    if (e.object && !islandRef.current?.children.includes(e.object)) {
      return;
    }
    setIsRotating(true);
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  }, [setIsRotating]);

  const handlePointerUp = useCallback(() => {
    setIsRotating(false);
  }, [setIsRotating]);

  const handlePointerMove = useCallback((e) => {
    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;
      if (islandRef.current) {
        islandRef.current.rotation.y += delta * 0.01 * Math.PI;
      }
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }, [isRotating, viewport.width]);

  // Touch events for mobile
  const handleTouchStart = useCallback((e) => {
    e.stopPropagation();
    setIsRotating(true);
    lastX.current = e.touches[0].clientX;
  }, [setIsRotating]);

  const handleTouchEnd = useCallback((e) => {
    e.stopPropagation();
    setIsRotating(false);
  }, [setIsRotating]);

  const handleTouchMove = useCallback((e) => {
    e.stopPropagation();
    if (isRotating) {
      const clientX = e.touches[0].clientX;
      const delta = (clientX - lastX.current) / viewport.width;
      if (islandRef.current) {
        islandRef.current.rotation.y += delta * 0.01 * Math.PI;
      }
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }, [isRotating, viewport.width]);

  // Key events for arrow key rotation
  const handleKeyDown = useCallback((e) => {
    if (e.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);
      if (islandRef.current) {
        islandRef.current.rotation.y += 0.01 * Math.PI;
      }
      rotationSpeed.current = 0.0125;
    } else if (e.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);
      if (islandRef.current) {
        islandRef.current.rotation.y -= 0.01 * Math.PI;
      }
      rotationSpeed.current = -0.0125;
    }
  }, [isRotating, setIsRotating]);

  const handleKeyUp = useCallback((e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
    }
  }, [setIsRotating]);

  useEffect(() => {
    // Only add global listeners for pointer up/move (to continue drag outside canvas)
    // Pointer down is handled via onPointerDown on the group itself
    window.addEventListener("pointerup", handlePointerUp);
    window.addEventListener("pointermove", handlePointerMove);
    window.addEventListener("touchend", handleTouchEnd);
    window.addEventListener("touchmove", handleTouchMove);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);

    return () => {
      window.removeEventListener("pointerup", handlePointerUp);
      window.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("touchend", handleTouchEnd);
      window.removeEventListener("touchmove", handleTouchMove);
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [handlePointerUp, handlePointerMove, handleTouchEnd, handleTouchMove, handleKeyDown, handleKeyUp]);

  // Animation loop: inertia rotation + floating levitation
  useFrame((_, delta) => {
    if (!islandRef.current) return;

    // Floating / levitation effect - exaggerated for visible bobbing
    floatOffset.current += delta * 0.9;
    const floatY = Math.sin(floatOffset.current) * 0.55;
    const floatTilt = Math.sin(floatOffset.current * 0.7) * 0.015;

    // Apply float to position
    if (props.position) {
      islandRef.current.position.y = props.position[1] + floatY;
    }
    // Gentle tilt that follows the float
    islandRef.current.rotation.x = (props.rotation?.[0] || 0.1) + floatTilt;
    islandRef.current.rotation.z = (props.rotation?.[2] || 0) + Math.sin(floatOffset.current * 0.5) * 0.012;

    // Inertia damping when not actively rotating
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.0001) {
        rotationSpeed.current = 0;
      }
      islandRef.current.rotation.y += rotationSpeed.current;
    }
  });

  return (
    <a.group ref={islandRef} {...props}>
      {/* Island meshes - all draggable */}
      <mesh
        geometry={nodes.polySurface944_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
        onPointerDown={(e) => { setIsRotating(true); lastX.current = e.clientX; }}
      />
      <mesh
        geometry={nodes.polySurface945_tree1_0.geometry}
        material={materials.PaletteMaterial001}
        onPointerDown={(e) => { setIsRotating(true); lastX.current = e.clientX; }}
      />
      <mesh
        geometry={nodes.polySurface946_tree2_0.geometry}
        material={materials.PaletteMaterial001}
        onPointerDown={(e) => { setIsRotating(true); lastX.current = e.clientX; }}
      />
      <mesh
        geometry={nodes.polySurface947_tree1_0.geometry}
        material={materials.PaletteMaterial001}
        onPointerDown={(e) => { setIsRotating(true); lastX.current = e.clientX; }}
      />
      <mesh
        geometry={nodes.polySurface948_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
        onPointerDown={(e) => { setIsRotating(true); lastX.current = e.clientX; }}
      />
      <mesh
        geometry={nodes.polySurface949_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
        onPointerDown={(e) => { setIsRotating(true); lastX.current = e.clientX; }}
      />
      <mesh
        geometry={nodes.pCube11_rocks1_0.geometry}
        material={materials.PaletteMaterial001}
        onPointerDown={(e) => { setIsRotating(true); lastX.current = e.clientX; }}
      />

      {/* Invisible clickable hotspot over the house area */}
      <mesh
        position={[0, 4, 2]}
        onPointerDown={(e) => {
          e.stopPropagation();
          pointerDownPos.current = { x: e.clientX, y: e.clientY };
        }}
        onPointerUp={(e) => {
          e.stopPropagation();
          const dx = Math.abs(e.clientX - pointerDownPos.current.x);
          const dy = Math.abs(e.clientY - pointerDownPos.current.y);
          if (dx < 8 && dy < 8 && onHouseClick) {
            onHouseClick();
          }
        }}
        onPointerOver={(e) => {
          e.stopPropagation();
          setHouseHovered(true);
        }}
        onPointerOut={() => setHouseHovered(false)}
      >
        <sphereGeometry args={[3, 16, 16]} />
        <meshBasicMaterial transparent opacity={0} />
        {houseHovered && (
          <Html center distanceFactor={12} style={{ pointerEvents: "none", userSelect: "none" }}>
            <div className="tooltip-label-big">
              <span>Contact Me</span>
              <span className="tooltip-arrow">&#8599;</span>
            </div>
          </Html>
        )}
      </mesh>
    </a.group>
  );
};

export default Island;
