/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Assassiinated (https://sketchfab.com/assassiinated)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-japanese-bell-temple-c203dd04fadd4cf8be80553a0c0cbb8c
Title: Floating Japanese Bell Temple
*/

import { useRef, useEffect, useCallback } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import islandScene from '../assets/3d/second.glb'

export default function SecondIsland({ isRotating, setIsRotating, autoRotate, ...props }) {
  const groupRef = useRef()
  const { viewport } = useThree()
  const { nodes, materials } = useGLTF(islandScene)

  const floatOffset = useRef(0)
  const lastX = useRef(0)
  const rotationSpeed = useRef(0)
  const dampingFactor = 0.95
  const AUTO_ROTATE_SPEED = 0.0015

  useFrame((_, delta) => {
    if (!groupRef.current) return
    floatOffset.current += delta * 0.9
    const floatY = Math.sin(floatOffset.current) * 0.55
    const floatTilt = Math.sin(floatOffset.current * 0.7) * 0.015
    if (props.position) {
      groupRef.current.position.y = props.position[1] + floatY
    }
    groupRef.current.rotation.x = (props.rotation?.[0] || 0) + floatTilt
    groupRef.current.rotation.z = (props.rotation?.[2] || 0) + Math.sin(floatOffset.current * 0.5) * 0.012
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor
      if (Math.abs(rotationSpeed.current) < 0.0001) rotationSpeed.current = 0
      groupRef.current.rotation.y += rotationSpeed.current
      // Slow continuous auto-rotation when enabled and inertia has settled
      if (autoRotate) {
        groupRef.current.rotation.y += AUTO_ROTATE_SPEED
      }
    }
  })

  const handlePointerMove = useCallback((e) => {
    if (isRotating && groupRef.current) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX
      const delta = (clientX - lastX.current) / viewport.width
      groupRef.current.rotation.y += delta * 0.01 * Math.PI
      lastX.current = clientX
      rotationSpeed.current = delta * 0.01 * Math.PI
    }
  }, [isRotating, viewport.width])

  const handlePointerUp = useCallback(() => {
    if (setIsRotating) setIsRotating(false)
  }, [setIsRotating])

  useEffect(() => {
    window.addEventListener('pointerup', handlePointerUp)
    window.addEventListener('pointermove', handlePointerMove)
    window.addEventListener('touchend', handlePointerUp)
    window.addEventListener('touchmove', handlePointerMove)
    return () => {
      window.removeEventListener('pointerup', handlePointerUp)
      window.removeEventListener('pointermove', handlePointerMove)
      window.removeEventListener('touchend', handlePointerUp)
      window.removeEventListener('touchmove', handlePointerMove)
    }
  }, [handlePointerUp, handlePointerMove])

  const startDrag = (e) => {
    e.stopPropagation()
    if (setIsRotating) setIsRotating(true)
    const clientX = e.touches ? e.touches[0].clientX : e.clientX
    lastX.current = clientX
  }

  return (
    <group ref={groupRef} {...props} dispose={null} onPointerDown={startDrag}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.RedWood}
        position={[-3.222, 1.712, -5.206]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.RedWood}
        position={[-3.225, 5.62, -5.089]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.RedWood}
        position={[-5.848, 3.884, -7.823]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.RedWood}
        position={[-5.854, 5.737, -2.512]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.003']}
        position={[-5.849, 6.926, -5.313]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.Tiling}
        position={[-5.881, 6.897, -5.237]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.roofbeam}
        position={[-5.888, 8.506, -5.216]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.roofring}
        position={[-5.876, 6.06, -5.244]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.RedWood}
        position={[-5.86, 1.546, -2.511]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.RedWood}
        position={[-8.536, 1.712, -5.188]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.RedWood}
        position={[-5.898, 1.546, -7.827]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.RedWood}
        position={[-3.248, 4.011, -5.206]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.RedWood}
        position={[-5.851, 3.884, -2.503]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.RedWood}
        position={[-8.536, 4.011, -5.188]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.RedWood}
        position={[-5.851, 4.81, -2.512]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.RedWood}
        position={[-8.536, 4.937, -5.188]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.RedWood}
        position={[-5.868, 4.81, -7.827]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.RedWood}
        position={[-3.226, 4.937, -5.206]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.RedWood}
        position={[-8.539, 5.62, -5.036]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.RedWood}
        position={[-5.876, 6.821, -5.167]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.RedWood}
        position={[-5.893, 5.737, -7.826]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.material}
        position={[-5.913, 3.918, -5.245]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials['Material.006']}
        position={[-5.911, 4.041, -5.247]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.Bell}
        position={[-5.908, 4.442, -5.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.RedWood}
        position={[-0.033, 2.742, 1.227]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.Bell}
        position={[-5.899, 4.655, -5.269]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.RedWood}
        position={[-8.476, 5.859, -9.74]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.RedWood}
        position={[-8.474, 5.859, -8.983]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.RedWood}
        position={[-8.474, 5.859, -8.605]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials.RedWood}
        position={[-8.473, 5.859, -8.227]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials.RedWood}
        position={[-8.472, 5.859, -7.848]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials.RedWood}
        position={[-8.472, 5.859, -7.47]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.RedWood}
        position={[-8.471, 5.859, -7.092]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.RedWood}
        position={[-8.47, 5.859, -6.714]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials.RedWood}
        position={[-8.47, 5.859, -6.335]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials.RedWood}
        position={[-8.469, 5.859, -5.957]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials.RedWood}
        position={[-8.468, 5.859, -5.579]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.RedWood}
        position={[-8.468, 5.859, -5.201]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.RedWood}
        position={[-8.467, 5.859, -4.823]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.RedWood}
        position={[-8.466, 5.859, -4.444]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials.RedWood}
        position={[-8.465, 5.859, -4.066]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.RedWood}
        position={[-8.465, 5.859, -3.688]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials.RedWood}
        position={[-8.464, 5.859, -3.31]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials.RedWood}
        position={[-8.463, 5.859, -2.931]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials.RedWood}
        position={[-8.463, 5.859, -2.553]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials.RedWood}
        position={[-8.462, 5.859, -2.175]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials.RedWood}
        position={[-8.461, 5.859, -1.797]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials.RedWood}
        position={[-8.461, 5.859, -1.418]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials.RedWood}
        position={[-8.46, 5.859, -1.04]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials.RedWood}
        position={[-8.459, 5.859, -0.662]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials.RedWood}
        position={[-3.278, 5.859, -0.683]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials.RedWood}
        position={[-3.279, 5.859, -1.061]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials.RedWood}
        position={[-3.28, 5.859, -1.439]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials.RedWood}
        position={[-3.28, 5.859, -1.817]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials.RedWood}
        position={[-3.281, 5.859, -2.195]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials.RedWood}
        position={[-3.282, 5.859, -2.574]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials.RedWood}
        position={[-3.282, 5.859, -2.952]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        material={materials.RedWood}
        position={[-3.283, 5.859, -3.33]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials.RedWood}
        position={[-3.284, 5.859, -3.708]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        material={materials.RedWood}
        position={[-3.284, 5.859, -4.087]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        material={materials.RedWood}
        position={[-3.285, 5.859, -4.465]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        material={materials.RedWood}
        position={[-3.286, 5.859, -4.843]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        material={materials.RedWood}
        position={[-3.286, 5.859, -5.221]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials.RedWood}
        position={[-3.287, 5.859, -5.6]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        material={materials.RedWood}
        position={[-3.288, 5.859, -5.978]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        material={materials.RedWood}
        position={[-3.289, 5.859, -6.356]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials.RedWood}
        position={[-3.289, 5.859, -6.734]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials.RedWood}
        position={[-3.29, 5.859, -7.113]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials.RedWood}
        position={[-3.291, 5.859, -7.491]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials.RedWood}
        position={[-3.291, 5.859, -7.869]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials.RedWood}
        position={[-3.292, 5.859, -8.247]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials.RedWood}
        position={[-3.293, 5.859, -8.626]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials.RedWood}
        position={[-3.293, 5.859, -9.004]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials.RedWood}
        position={[-3.294, 5.859, -9.382]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials.RedWood}
        position={[-3.295, 5.859, -9.76]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials.RedWood}
        position={[-8.475, 5.859, -9.361]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        material={materials.RedWood}
        position={[-0.033, 3.253, 1.227]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials['Material.006']}
        position={[-5.92, 2.746, -5.264]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials['Material.004']}
        position={[-7.189, -5.158, -4.537]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials['Material.004']}
        position={[-2.419, -4.234, -6.269]}
        rotation={[0, 0.786, 0]}
        scale={1.368}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials['Material.004']}
        position={[-7.72, -3.73, -2.593]}
        rotation={[0, 0.786, 0]}
        scale={0.788}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials['Material.004']}
        position={[-6.689, -2.46, -8.112]}
        rotation={[0, 0.786, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials['Material.004']}
        position={[-4.965, -4.882, -2.254]}
        rotation={[0, 1.552, 0]}
        scale={0.788}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials['Material.004']}
        position={[-6.689, -4.495, -8.112]}
        rotation={[0, 0.786, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_172.geometry}
        material={materials['Material.004']}
        position={[-3.18, -5.75, -3.86]}
        rotation={[0, 0, -1.859]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_174.geometry}
        material={materials['Material.004']}
        position={[-5.155, -7.424, -3.816]}
        rotation={[0, 0, -1.302]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials.RedWood}
        position={[-4.789, 3.217, 8.726]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_178.geometry}
        material={materials['Material.004']}
        position={[-6.14, -3.715, 10.034]}
        rotation={[0, 0.786, 0]}
        scale={0.371}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_180.geometry}
        material={materials['Material.004']}
        position={[-3.932, -3.527, 8.292]}
        rotation={[-Math.PI, 0.638, -Math.PI]}
        scale={0.371}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_182.geometry}
        material={materials['Material.004']}
        position={[-5.413, -2.578, 8.539]}
        rotation={[2.931, -0.415, 0.244]}
        scale={0.371}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials['Material.004']}
        position={[-4.733, -3.315, 9.893]}
        rotation={[-Math.PI, 1.236, -Math.PI]}
        scale={0.371}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_186.geometry}
        material={materials['Material.004']}
        position={[-5.339, -3.126, 7.147]}
        rotation={[-Math.PI, -0.482, -Math.PI]}
        scale={0.371}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_188.geometry}
        material={materials['Material.004']}
        position={[-6.12, -2.437, 7.064]}
        rotation={[Math.PI, 0.931, -2.177]}
        scale={0.216}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_190.geometry}
        material={materials['Material.004']}
        position={[-6.709, -2.744, 7.332]}
        rotation={[Math.PI, 0.931, -2.177]}
        scale={0.127}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_192.geometry}
        material={materials['Material.004']}
        position={[-7.138, -2.214, 7.397]}
        rotation={[Math.PI, 0.931, -2.177]}
        scale={0.127}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_194.geometry}
        material={materials['Material.004']}
        position={[-3.789, -2.809, 7.879]}
        rotation={[-Math.PI, 0.638, -Math.PI]}
        scale={[0.115, 0.115, 0.055]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_196.geometry}
        material={materials['Material.004']}
        position={[-4.156, -4.349, 10.034]}
        rotation={[0, 0.786, 0]}
        scale={0.371}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_198.geometry}
        material={materials['Material.004']}
        position={[-3.58, -4.79, 9.166]}
        rotation={[-Math.PI, 0.312, -Math.PI]}
        scale={[0.28, 0.316, 0.175]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_200.geometry}
        material={materials.RedWood}
        position={[-7.058, 1.767, 8.735]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_202.geometry}
        material={materials.RedWood}
        position={[-7.054, 3.735, 8.736]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_204.geometry}
        material={materials.RedWood}
        position={[-3.422, 3.755, 8.736]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_206.geometry}
        material={materials.RedWood}
        position={[-3.414, 3.18, 8.747]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_208.geometry}
        material={materials.RedWood}
        position={[-7.057, 3.18, 8.747]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_210.geometry}
        material={materials.RedWood}
        position={[-5.245, 2.912, 8.747]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_212.geometry}
        material={materials.RedWood}
        position={[-5.246, 4.041, 8.719]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_214.geometry}
        material={materials.Shrine}
        position={[-3.426, -0.665, 8.735]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_216.geometry}
        material={materials.Shrine}
        position={[-7.056, -0.63, 8.735]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_218.geometry}
        material={materials.Shrine}
        position={[-5.246, 4.401, 8.714]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_220.geometry}
        material={materials.RedWood}
        position={[-5.245, 2.912, 8.747]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3.175, 0.18, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_222.geometry}
        material={materials['Material.004']}
        position={[-4.138, -6.557, -3.247]}
        rotation={[0, 1.552, 0]}
        scale={0.463}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_224.geometry}
        material={materials['Material.004']}
        position={[-8.803, -6.213, -6.198]}
        rotation={[0, 0, -0.69]}
        scale={0.423}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_226.geometry}
        material={materials['Material.004']}
        position={[-1.907, -2.756, -7.717]}
        rotation={[-3.114, 0.797, -1.59]}
        scale={[0.297, 0.763, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_228.geometry}
        material={materials['Material.004']}
        position={[-1.66, -2.303, -7.717]}
        rotation={[2.221, 0.236, -2.328]}
        scale={[0.297, 0.259, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_230.geometry}
        material={materials['Material.004']}
        position={[-7.189, -4.856, -2.88]}
        rotation={[0, 0, 1.005]}
        scale={[0.479, 1, 0.265]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_232.geometry}
        material={materials['Material.004']}
        position={[-5.282, -3.424, -8.875]}
        rotation={[0.002, 0.688, 1.588]}
        scale={[0.297, 0.763, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_234.geometry}
        material={materials['Material.004']}
        position={[-9.614, -2.957, -7.041]}
        rotation={[0.002, 0.688, 1.588]}
        scale={[0.297, 0.763, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_236.geometry}
        material={materials['Material.004']}
        position={[-4.482, -6.202, -7.309]}
        rotation={[0.002, 0.688, 1.588]}
        scale={[0.297, 0.763, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_238.geometry}
        material={materials['Material.004']}
        position={[-4.138, -7.078, -4.689]}
        rotation={[0, 1.552, 0]}
        scale={0.463}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_240.geometry}
        material={materials['Material.004']}
        position={[-6.578, -7.424, -3.816]}
        rotation={[0, 0, -1.302]}
        scale={0.547}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_242.geometry}
        material={materials['Material.004']}
        position={[-5.56, -7.424, -1.724]}
        rotation={[0, 0, -1.302]}
        scale={0.397}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_244.geometry}
        material={materials.Material}
        position={[9.685, 4.216, -2.25]}
        scale={[1, 1, 2.014]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_246.geometry}
        material={materials.Material}
        position={[9.685, 4.216, -2.25]}
        scale={[1, 1, 2.014]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_248.geometry}
        material={materials.Material}
        position={[0.586, -0.897, -3.232]}
        rotation={[0.272, 0, 0]}
        scale={[1, 1, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_250.geometry}
        material={materials.Material}
        position={[0.677, -0.874, -3.821]}
        rotation={[-0.1, 0.618, 0]}
        scale={[1, 1, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_252.geometry}
        material={materials.Material}
        position={[0.532, -0.874, -6.548]}
        rotation={[-0.1, 0.618, 0]}
        scale={[1, 1, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_254.geometry}
        material={materials.Material}
        position={[0.155, -2.087, -8.023]}
        rotation={[-0.1, 0.951, 0]}
        scale={[1, 1.831, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_256.geometry}
        material={materials.Material}
        position={[0.326, -0.549, -7.228]}
        rotation={[-0.1, 0.951, 0]}
        scale={[0.639, 0.639, 0.94]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_258.geometry}
        material={materials.Material}
        position={[-0.139, -1.275, -8.973]}
        rotation={[-0.1, 0.951, 0]}
        scale={[1, 1.147, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_260.geometry}
        material={materials.Material}
        position={[-1.408, -1.117, -11.06]}
        rotation={[-0.1, 1.349, 0]}
        scale={[1, 1.147, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_262.geometry}
        material={materials.Material}
        position={[-1.981, -1.122, -11.546]}
        rotation={[3.042, 0.942, -Math.PI]}
        scale={[1, 1.147, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_264.geometry}
        material={materials.Material}
        position={[-1.981, -1.658, -9.762]}
        rotation={[3.042, 0.962, -Math.PI]}
        scale={[1, 1.147, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_266.geometry}
        material={materials.Material}
        position={[-1.837, -1.506, -9.442]}
        rotation={[-0.1, 1.115, 0]}
        scale={[1, 1.147, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_268.geometry}
        material={materials.Material}
        position={[-5.816, -1.932, -11.997]}
        rotation={[3.042, 0.676, -Math.PI]}
        scale={[1, 1.741, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_270.geometry}
        material={materials.Material}
        position={[-6.397, -0.525, -12.179]}
        rotation={[3.042, 0.676, -Math.PI]}
        scale={[1, 0.752, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_272.geometry}
        material={materials.Material}
        position={[-8.188, -0.458, -11.52]}
        rotation={[3.042, 0.366, -Math.PI]}
        scale={[1.659, 0.642, 1.718]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_274.geometry}
        material={materials.Material}
        position={[-7.136, -0.26, -12.032]}
        rotation={[3.042, 0.529, -Math.PI]}
        scale={[1, 0.421, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_276.geometry}
        material={materials.Material}
        position={[-12.553, -0.597, -4.877]}
        rotation={[-0.1, 0.45, 0]}
        scale={[0.722, 0.722, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_278.geometry}
        material={materials.Material}
        position={[-12.59, -1.318, -5.303]}
        rotation={[-0.1, 0.45, 0]}
        scale={[1, 1.231, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_280.geometry}
        material={materials.Material}
        position={[-9.033, -0.584, -0.638]}
        rotation={[3.042, 1.148, Math.PI]}
        scale={[0.722, 0.722, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_282.geometry}
        material={materials.Material}
        position={[-8.545, -0.584, -0.428]}
        rotation={[3.042, 1.148, Math.PI]}
        scale={[0.722, 0.722, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_284.geometry}
        material={materials.Material}
        position={[-7.914, -0.989, -0.351]}
        rotation={[3.042, 1.148, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_286.geometry}
        material={materials.Material}
        position={[-4.32, -0.681, 0.105]}
        rotation={[3.042, 1.521, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_288.geometry}
        material={materials.Material}
        position={[-3.922, -0.681, 0.373]}
        rotation={[3.042, 1.521, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_290.geometry}
        material={materials.Material}
        position={[-3.655, -0.681, 0.591]}
        rotation={[3.042, 1.521, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_292.geometry}
        material={materials.Material}
        position={[-3.257, -0.681, 0.859]}
        rotation={[3.042, 1.521, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_294.geometry}
        material={materials.Material}
        position={[-4.443, -0.854, 0.195]}
        rotation={[3.042, 1.521, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_296.geometry}
        material={materials.Material}
        position={[-4.045, -1.491, 0.549]}
        rotation={[3.042, 1.521, Math.PI]}
        scale={[0.722, 1.698, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_298.geometry}
        material={materials.Material}
        position={[-3.447, -1.052, 0.913]}
        rotation={[3.042, 1.521, Math.PI]}
        scale={[0.722, 1.185, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_300.geometry}
        material={materials.Material}
        position={[-2.543, -0.785, 1.188]}
        rotation={[3.042, 0.276, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_302.geometry}
        material={materials.Material}
        position={[-2.162, -0.841, 0.901]}
        rotation={[3.042, 0.276, Math.PI]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_304.geometry}
        material={materials.Material}
        position={[-1.583, -0.479, 0.433]}
        rotation={[3.042, 0.276, Math.PI]}
        scale={[0.722, 0.687, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_306.geometry}
        material={materials.Material}
        position={[-3.097, -0.785, 1.185]}
        rotation={[-0.1, 1.501, 0]}
        scale={[0.722, 1.003, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_308.geometry}
        material={materials.Material}
        position={[-12.587, -0.812, -6.152]}
        rotation={[-0.1, 0.45, 0]}
        scale={[1, 0.839, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_310.geometry}
        material={materials.Material}
        position={[-3.953, -2.69, -1.776]}
        rotation={[3.042, 0.276, Math.PI]}
        scale={[0.722, 0.687, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_312.geometry}
        material={materials.Material}
        position={[-5.865, -1.823, -1.773]}
        rotation={[-0.1, -0.853, 0]}
        scale={[0.722, 0.687, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_314.geometry}
        material={materials.Material}
        position={[-5.865, -1.823, 6.7]}
        rotation={[-0.1, -0.977, 0]}
        scale={[0.722, 0.687, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_316.geometry}
        material={materials.Material}
        position={[-7.566, -1.908, 9.57]}
        rotation={[-0.1, 0.469, 0]}
        scale={[0.722, 0.687, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_318.geometry}
        material={materials.Material}
        position={[-7.212, -1.908, 10.31]}
        rotation={[-0.1, 1.517, 0]}
        scale={[0.722, 0.687, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_320.geometry}
        material={materials.Material}
        position={[-5.52, -1.581, 11.158]}
        rotation={[3.042, 1.051, Math.PI]}
        scale={[0.559, 0.374, 0.798]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_322.geometry}
        material={materials.Material}
        position={[-5.196, -1.781, 11.158]}
        rotation={[3.042, 1.051, Math.PI]}
        scale={[0.559, 0.567, 0.798]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_324.geometry}
        material={materials.Material}
        position={[-2.275, -1.75, 9.407]}
        rotation={[3.042, -0.466, Math.PI]}
        scale={[0.559, 0.567, 0.798]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_326.geometry}
        material={materials.Material}
        position={[-2.2, -1.472, 8.965]}
        rotation={[3.042, -0.466, Math.PI]}
        scale={[0.559, 0.309, 0.798]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_328.geometry}
        material={materials.Material}
        position={[-4.125, -2.206, 6.913]}
        rotation={[-0.1, -1.089, 0]}
        scale={[0.722, 1.038, 1.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_330.geometry}
        material={materials['Material.002']}
        position={[-3.513, 0.492, 0.354]}
        rotation={[0, -0.596, 0]}
        scale={[1.775, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_332.geometry}
        material={materials['Material.002']}
        position={[-2.545, 0.395, 0.605]}
        rotation={[0, 0.398, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_334.geometry}
        material={materials['Material.002']}
        position={[-3.286, 0.272, -1.996]}
        rotation={[0, -0.034, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_336.geometry}
        material={materials['Material.002']}
        position={[-2.837, 0.272, -2.184]}
        rotation={[0, 0.906, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_338.geometry}
        material={materials['Material.002']}
        position={[-3.099, 0.272, -3.04]}
        rotation={[0, -0.183, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_340.geometry}
        material={materials['Material.002']}
        position={[-5.97, 0.272, -1.983]}
        rotation={[0, -0.034, 0]}
        scale={[1.325, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_342.geometry}
        material={materials['Material.002']}
        position={[-5.386, 0.307, -2.235]}
        rotation={[0, 0.907, 0]}
        scale={[0.959, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_344.geometry}
        material={materials['Material.002']}
        position={[-8.667, 0.249, -1.983]}
        rotation={[0, -0.034, 0]}
        scale={[0.811, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_346.geometry}
        material={materials['Material.002']}
        position={[-8.354, 0.478, -1.983]}
        rotation={[0, -0.034, 0]}
        scale={[0.811, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_348.geometry}
        material={materials['Material.002']}
        position={[-8.099, 0.341, -2.202]}
        rotation={[0, 1.021, 0]}
        scale={[0.811, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_350.geometry}
        material={materials['Material.002']}
        position={[-9, 0.478, -2.202]}
        rotation={[0, -1.034, 0]}
        scale={[0.811, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_352.geometry}
        material={materials['Material.002']}
        position={[-5.869, 0.272, -3.045]}
        rotation={[0, -0.183, 0]}
        scale={[1, 1.525, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_354.geometry}
        material={materials['Material.002']}
        position={[-8.508, 0.272, -3.044]}
        rotation={[0, -0.183, 0]}
        scale={[1, 0.828, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_356.geometry}
        material={materials['Material.002']}
        position={[-8.595, 0.331, -7.294]}
        rotation={[0, -0.183, 0]}
        scale={[1, 0.828, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_358.geometry}
        material={materials['Material.002']}
        position={[-8.505, 0.331, -8.389]}
        rotation={[0, -0.183, 0]}
        scale={[0.725, 1.044, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_360.geometry}
        material={materials['Material.002']}
        position={[-8.944, 0.331, -8.218]}
        rotation={[0, 0.613, 0]}
        scale={[0.725, 1.044, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_362.geometry}
        material={materials['Material.002']}
        position={[-5.897, 0.331, -8.389]}
        rotation={[0, -0.183, 0]}
        scale={[0.725, 1.044, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_364.geometry}
        material={materials['Material.002']}
        position={[-6.323, 0.352, -8.239]}
        rotation={[0, 0.789, 0]}
        scale={[0.725, 1.044, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_366.geometry}
        material={materials['Material.002']}
        position={[-5.725, 0.352, -7.362]}
        rotation={[0, 0.262, 0]}
        scale={[0.725, 1.044, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_368.geometry}
        material={materials['Material.002']}
        position={[-3.166, 0.331, -8.389]}
        rotation={[0, -0.183, 0]}
        scale={[0.725, 1.044, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_370.geometry}
        material={materials['Material.002']}
        position={[-2.672, 0.331, -7.846]}
        rotation={[0, 1.518, 0]}
        scale={[0.725, 0.789, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_372.geometry}
        material={materials['Material.002']}
        position={[-5.897, 0.546, -12.153]}
        rotation={[0, 0.167, 0]}
        scale={[0.725, 0.986, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_374.geometry}
        material={materials['Material.002']}
        position={[-6.29, 0.559, -12.111]}
        rotation={[0, 0.003, 0]}
        scale={[0.725, 0.986, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_376.geometry}
        material={materials['Material.002']}
        position={[-7.411, 0.483, -11.691]}
        rotation={[0, 0.458, 0]}
        scale={[0.725, 0.986, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_378.geometry}
        material={materials['Material.002']}
        position={[-0.295, 0.477, -8.825]}
        rotation={[0, -1.303, 0]}
        scale={[2.091, 0.604, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_380.geometry}
        material={materials['Material.002']}
        position={[-12.315, 0.477, -5.795]}
        rotation={[0, 1.448, 0]}
        scale={[3.365, 0.604, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_382.geometry}
        material={materials['Material.002']}
        position={[-3.532, -1.063, 9.152]}
        rotation={[0, -0.266, 0]}
        scale={[0.894, 0.84, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_384.geometry}
        material={materials['Material.002']}
        position={[-7.053, -1.058, 9.137]}
        rotation={[0, -0.034, 0]}
        scale={[0.894, 0.84, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_386.geometry}
        material={materials['Material.002']}
        position={[-6.746, -1.058, 8.433]}
        rotation={[0, -0.744, 0]}
        scale={[0.894, 0.84, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_388.geometry}
        material={materials['Material.002']}
        position={[-3.106, -1.041, 8.977]}
        rotation={[0, 0.917, 0]}
        scale={[0.894, 0.84, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_390.geometry}
        material={materials['Material.002']}
        position={[-5.863, -0.91, 6.742]}
        rotation={[0, -0.088, 0]}
        scale={[0.894, 0.84, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_392.geometry}
        material={materials['Material.002']}
        position={[-5.37, -0.91, 11.108]}
        rotation={[0, 0.057, 0]}
        scale={[0.894, 0.619, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_394.geometry}
        material={materials['Material.002']}
        position={[0.176, 0.477, -7.293]}
        rotation={[0, -1.303, 0]}
        scale={[1.556, 0.604, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_396.geometry}
        material={materials['Material.002']}
        position={[0.063, 0.474, -2.614]}
        rotation={[Math.PI, -1.455, Math.PI]}
        scale={[2.112, 0.604, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_398.geometry}
        material={materials.island1}
        position={[-6.002, -1.145, -5.431]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_400.geometry}
        material={materials.material_0}
        position={[-8.543, 0.558, -7.828]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={1.135}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_402.geometry}
        material={materials.RedWood}
        position={[-8.554, 3.254, -7.821]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_404.geometry}
        material={materials.RedWood}
        position={[-8.53, 3.697, -2.504]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_406.geometry}
        material={materials.RedWood}
        position={[-5.888, 4.217, -2.507]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_408.geometry}
        material={materials.RedWood}
        position={[-3.211, 3.254, -2.518]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_410.geometry}
        material={materials.RedWood}
        position={[-3.24, 3.254, -7.876]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_412.geometry}
        material={materials.RedWood}
        position={[-5.906, 4.215, -7.822]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_414.geometry}
        material={materials.island1}
        position={[-6.002, -1.107, -5.431]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_416.geometry}
        material={materials.material_0}
        position={[-8.53, 0.559, -2.52]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={1.092}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_418.geometry}
        material={materials.material_0}
        position={[-5.888, 0.559, -2.522]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={1.081}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_420.geometry}
        material={materials.material_0}
        position={[-3.224, 0.558, -2.537]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={[1.082, 1.081, 1.082]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_422.geometry}
        material={materials.material_0}
        position={[-3.241, 0.558, -7.846]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={1.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_424.geometry}
        material={materials.material_0}
        position={[-5.906, 0.556, -7.837]}
        rotation={[-Math.PI, -0.002, -Math.PI]}
        scale={1.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_426.geometry}
        material={materials.island1}
        position={[-5.206, -1.711, 8.735]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.503, 0.439, 0.382]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_428.geometry}
        material={materials.island1}
        position={[-5.206, -1.695, 8.735]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.501, 0.437, 0.381]}
      />
    </group>
  )
}

useGLTF.preload(islandScene)
